# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-01 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180501_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
